# version: '3.9'
# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#       target: dev
#     ports:
#       - 3000:3000
#     volumes:
#       - ./src:/app/src
#     depends_on:
#       - db

#   db:
#     image: postgres
#     restart: always
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_PASSWORD: postgres

version: "3.9"
services:
  nest-backend:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
      target: pro
    environment:
      - PORT=4040
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@localhost:9876/postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=postgres
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - 9876:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
networks:
  backend_network:
    driver: bridge
volumes:
  postgres_data: {}
  redis:
    driver: local
  mysql_db: